### ISSUE TITLE
test(prisma): mocking database client for unit test

### ISSUE THREAD

**Issue by mu-hun** [reflation/backend#10]
> @ahastudio : _"DB를 가짜로 다루는 걸 시도해 보세요. 레이어를 분리하면 굉장히 쉬워집니다."_

단위 테스트 전후로 DB를 정리해야 되는데, 지난 prisma 적용 작업(#8)에서 미쳐 드리지 못해서 미안합니다.

별도의 가상 prisma client 를 사용 해보면 좋을 것 같아 https://github.com/prisma/prisma/issues/3898 이슈와 [관련 예제](https://github.com/prisma/prisma/blob/master/cli/packages/prisma-cli-core/src/test/mock-client.ts)를 제가 읽어봤지만 어떻게 하면 좋을지 잘 모르는 상황입니다.

이 부분만 하면 백단 DB가 거의 마무리 될 것 같은데 혹시 @BasixKOR 님이 맡아주실 수 있으실까요?

괜찮으시다면 Assigned 해드리겠습니다.

**Comment by x86chi** [comment]
회신이 없으신 것 같아 좀 부담스러워하시는 것 같네요. 그러면 제가 내일 시간을 투자해서 해결해보겠습니다.

**Comment by ahastudio** [comment]
Prisma를 그대로 Mocking하는 것보다 Persistence Layer를 나눠서 처리하는 게 낫습니다.

기존에 Repository나 DAO 등을 써본 적이 있다면 그 아이디어를 그대로 사용하시면 됩니다.

**Comment by ahastudio** [comment]
지금도 `src/models/index.ts`로 분리가 돼있네요. 그쪽을 그대로 활용하시면 됩니다.

**Comment by ahastudio** [comment]
`__mocks__`를 활용하셔도 되고, `jest.fn`을 활용하셔도 됩니다.

- <https://jestjs.io/docs/en/manual-mocks.html>
- <https://jestjs.io/docs/en/mock-function-api>

**Comment by ahastudio** [comment]
지금은 `loginRoute`를 테스트하면서 `createUser`를 mocking해야 하는데, 이게 예측하기 좋은지 질문하면 좋을 것 같습니다.

전통적으론 “Presentation Layer (UI Layer)”와 “Application Layer (Service Layer)”를 나눠서 웹에선 DB에 관련된 걸 직접적으로 몰라도 되게 합니다. 일단 그대로 가다가 뭔가 불편함이 느껴지면 Application Layer를 도입해 보세요.

**Comment by x86chi** [comment]
```
Basix, [10/29/19, 12:03 PM]
그건 그렇고 mocking은 상당히 어려운 이슈가 될 것 같네요... CI 환경에서 Prisma를 돌리는 건 무리려나요?

Basix, [10/29/19, 12:10 PM]
https://www.prisma.io/docs/prisma-server/demo-servers-prisma-cloud-jfr3/ 아니면 Prisma에서 제공하는 Demo Server을 사용하는 방법도 있겠네요

팔육칩(muhun), [10/29/19, 1:00 PM]
튜토리얼을 잠깐 봐봤습니다.. https://www.youtube.com/watch?v=Wjt9Hy_BI2M 로컬의 도커 컨테이너로 DB를 운영하는 방식보단 간편하게 보이네요.

Basix, [10/29/19, 1:00 PM]
그러면 제가 클라우드로 변경 작업해둘까요?

팔육칩(muhun), [10/29/19, 1:01 PM]
네 그럽시다 :D

Basix, [10/29/19, 1:01 PM]
알겠습니다!
```

@ahastudio 조언 감사합니다. 이미 [Prisma cloud](https://www.prisma.io/cloud)로 의사 결정을 내린 상황이라 빠르게 성공하거나 실패해본 뒤 제안해주신 방법을 노력하겠습니다.

**Comment by mu-hun** [comment]
`res.body` assertion 아직 안함.

**Comment by mu-hun** [comment]
#15 에서 해결함
