### ISSUE TITLE
test: sent ‘undefined’ body on unit test environment

### ISSUE THREAD

**Issue by mu-hun** [reflation/backend#2]
> target commit is 89b6cba

## Unit test

```js
  ● GET /GPA › send vaild token › return 200 status code

    assert.to be a string(received, expected)

    Expected value to be a string to:
      undefined
    Received:
      {}

    Difference:

      Comparing two different types of values. Expected undefined but received object.
```

## Manual E2E test

<img width="338" alt="Screen Shot 2019-10-22 at 6 10 53 PM" src="https://user-images.githubusercontent.com/5278201/67279010-27a0c500-f505-11e9-8e24-52281813de17.png">

But end-to-end test was sent expect value

**Comment by mu-hun** [comment]
@BasixKOR 평점 파싱은 데모라서 그냥 패스하고 싶은데, body 자체가 undefined 인 것 같아 좀 고민이네요.

**Comment by BasixKOR** [comment]
`POST /login` 테스트 코드에서 `body`를 받아와 토큰으로 저장하는 부분에서 `body`가 Object {}로 나오네요. body 대신 text를 사용했더니 토큰이 정상적으로 받아와지는 것 같습니다.

**Comment by x86chi** [comment]
아하, 그렇군요. 추후 패치 커밋을 작성하겠습니다.

**Comment by mu-hun** [comment]
(plain/text 대신에 urlencoded/JSON 으로) #9 를 적용하고 다시 확인하겠습니다.

**Comment by mu-hun** [comment]
#13 과정 중에 해결함
