### ISSUE TITLE
refact: use urlencoded or JSON type for request and response

### ISSUE THREAD

**Issue by mu-hun** [reflation/backend#9]
유의미한 데이터 전달에는 plain/text 보다 key: value 가 더 어울릴 것 같습니다.

**Comment by BasixKOR** [comment]
GET이나 HEAD 등 쿼리 스트링이 URL에 들어가는 경우 이외에는 JSON으로 body를 통일하면 어떨까요?

**Comment by mu-hun** [comment]
POST(`form/urlencoded`) 를 제외한다는 얘기신가요? 괜찮을 것 같네요.

**Comment by mu-hun** [comment]
## ... is not assignable to parameter of type `CallbackHandler`

> [테스트 소스 gist 링크 첨부](https://gist.github.com/x86chi/928b02fd938bbf91eb21a6fe79ea5d33)

```ts
TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/index.test.ts:48:14 - error TS2345: Argument of type '(err: any, res: TypeRes<{ gpa: string; }>) => void' is not assignable to parameter of type 'CallbackHandler'.
      Types of parameters 'res' and 'res' are incompatible.
        Type 'Response' is missing the following properties from type 'TypeRes<{ gpa: string; }>': sendStatus, send, json, jsonp, and 53 more.

    48         .end((err, res: TypeRes<{ gpa: string }>) => {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/index.test.ts:75:14 - error TS2345: Argument of type '(err: any, res: TypeRes<{ gpa: string; }>) => void' is not assignable to parameter of type 'CallbackHandler'.
      Types of parameters 'res' and 'res' are incompatible.
        Type 'Response' is missing the following properties from type 'TypeRes<{ gpa: string; }>': sendStatus, send, json, jsonp, and 53 more.

    75         .end((err, res: TypeRes<{ gpa: string }>) => {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## `TypeRes` 내용

```ts
import { Response } from 'express'
export interface TypeRes<T> extends Response {
  body: T
}
```

위 부분에 일부 타입을 놓치고 있습니다. 혹시 `CallbackHandler` 파라미터 타입에 대해 아시는 내용이 있으신가요?

**Comment by BasixKOR** [comment]
express의 Response 대신 supertest의 Response를 extend해야 하지 않을까요?

**Comment by mu-hun** [comment]
`supertest.Response`로 바뀌보니 해결되었습니다. (1b0952b 참고)

하지만 prisma의 타입 정의 문서에서 `User.emailid` 스키마가 매칭이 안되는 상황입니다. (73423e5 참고)

분명히 모든 문서 내에 `User.emailid` 속성을 정의했는데 놓친 부분이 있는지 리뷰 부탁드립니다!

**Comment by BasixKOR** [comment]
@x86chi `src/models/prisma` 내 파일은 `prisma generate`로 자동 생성되는 파일이라 따로 건드리면 안 됩니다 😢

Prisma 내 타입 정의를 변경하실 경우는 prisma 폴더에서 `datamodel.prisma`를 수정해주셔야 합니다. 이 점은 이후에 따로 문서에 적어두겠습니다. 현재 코드는 제가 수정한 뒤 커밋할게요! 😄

**Comment by x86chi** [comment]
아하 그렇군요. 문서를 따로 참조하지 않고 대강 유추해서 수정한 점 미안합니다 :(

**Comment by mu-hun** [comment]
앗, 미안합니다. 셀프 리뷰를 해보니  `prisma/datamodel.prisma`에서 [타입을 이미 `mailid`로](https://github.com/x86chi/node-ts-backend/blob/refact/prisma-schema/prisma/datamodel.prisma#L3) 갱신을 해뒀네요.

**Comment by ahastudio** [comment]
아주 특별한 경우가 아니면 `body`를 그대로 쓰지 않습니다.

`이름`이 아니라 `{"name":"이름"}`을 전달하고, `토큰`이 아니라 `{"token":"토큰"}`을 받죠.

다른 (좋은) 곳에서 어떻게 하고 있는지 참고하시면 좋습니다.
